server:
  port: 9080

database:
  dsn: root:root@tcp(127.0.0.1:3306)/blog_project?charset=utf8mb4&parseTime=True&loc=Local

log:
  level: "debug"
  filename: "logs/app.log"
  max_size: 100  # 单个文件最大 100MB
  max_backups: 7 # 最多保留 7 个旧日志
  max_age: 30 # 日志最多保留 30 天
  compress: true  # 是否压缩

cors:
  allowedOrigins: ["*"]
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE

redis:
  host: 127.0.0.1:6379
