server:
  port: 9080

database:
  dsn: root:root@tcp(127.0.0.1:3306)/blog_project?charset=utf8mb4&parseTime=True&loc=Local

log:
  level: "error"
  filename: "logs/app.log"
  max_size: 100
  max_backups: 7
  max_age: 30
  compress: true

cors:
  allowedOrigins: ["*"] # 这里根据实际生产环境地址做出修改
  allowedMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"

redis:
  host: 127.0.0.1:6379

contract:
  httpUrl: https://eth-mainnet.g.alchemy.com/v2/27NL_0zlbK15k86qzL4emhJMRO-kDoPX
  websocketUrl: wss://eth-mainnet.g.alchemy.com/v2/27NL_0zlbK15k86qzL4emhJMRO-kDoPX
  erc20Contract:
    address: 0x3f3648cdc599094ff35353f815ad505c487b618c
    erc20BlockNumber: 9101518