basePath: /api
definitions:
  response.ResultResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
host: localhost:9080
info:
  contact: {}
  description: 这是一个基于 Gin 的 个人博客系统后端API
  title: 个人博客系统后端 API 文档
  version: "1.0"
paths:
  /login:
    get:
      description: 用户通过用户名和密码登录
      parameters:
      - in: formData
        name: password
        required: true
        type: string
      - in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 用户登录
      tags:
      - 登录
  /login/register:
    post:
      description: 注册一个用户
      parameters:
      - in: formData
        name: authenticationFlag
        type: string
      - in: formData
        name: email
        type: string
      - in: formData
        name: id
        type: integer
      - in: formData
        name: password
        type: string
      - in: formData
        name: userName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 注册用户
      tags:
      - 登录
  /v1/comments:
    get:
      description: 获取文章评论列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 获取文章评论列表
      tags:
      - 评论
    post:
      description: 创建评论
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 创建评论
      tags:
      - 评论
  /v1/posts:
    post:
      description: 用户创建文章
      parameters:
      - in: formData
        name: content
        type: string
      - in: formData
        name: createdAt
        type: string
      - in: formData
        name: id
        type: integer
      - in: formData
        name: title
        type: string
      - in: formData
        name: userId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 创建文章接口
      tags:
      - 文章
  /v1/posts/:id:
    delete:
      description: 删除文章
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 删除文章
      tags:
      - 文章
  /v1/posts/detail:
    get:
      description: 获取文章详情
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 获取文章详情
      tags:
      - 文章
  /v1/posts/list:
    get:
      description: 获取文章列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 获取文章列表
      tags:
      - 文章
  /v1/posts/modify:
    put:
      description: 修改文章
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 修改文章
      tags:
      - 文章
  /v1/users/auth:
    get:
      description: 用户通过token和邮箱认证
      parameters:
      - in: formData
        name: email
        type: string
      - in: formData
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResultResponse'
      summary: 认证用户
      tags:
      - 用户
swagger: "2.0"
